multigpu: False
max_epoch: 30
checkpoint_dir: 'checkpoint'
generator:
  batch_size: 1
  input_channel: 441
  output_channel: 10
  dropout_rate: 0.5
  adam_beta1: 0.9
  adam_beta2: 0.999
  learning_rate: 0.0001
  milestones: [5, 10, 15, 20, 25, 30]
  gamma: 0.1
discriminator:
  batch_size: 1
  input_channel: 451
  adam_beta1: 0.9
  adam_beta2: 0.999
  learning_rate: 0.00001
  milestones: [15, 30, 45, 60, 75, 90]
  gamma: 0.1
loss:
  alpha: [0.25, 0.25, 0.25, 0.25, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75]
  beta: 1.0
  gamma: 2.0
  lambda: 1.0